---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: ubuntu
  - name: rocky
    image: rockylinux/rockylinux:9
provisioner:
  name: ansible
verifier:
  name: ansible
